"""Place suggestions via the Google Places API (New) — key required.

Docs: https://developers.google.com/maps/documentation/places/web-service/place-autocomplete

The web-service key stays on the server; the mobile app only ever sees this
proxy's normalized responses. Session tokens (one per user search session,
generated by the app) are passed straight through so Google bills a typing
+ selection sequence as a single Autocomplete session.

Predictions from the New API do not carry coordinates by design: the client
resolves the selected prediction through /v1/places/details (same session
token), which returns the place's real location. Nothing is invented here.
"""
from __future__ import annotations

import httpx

from ..config import get_settings
from ..core.timeutil import tz_at
from ..domain.geo import GeoPoint
from .google_common import ProviderError, make_client

_PREDICTION_FIELD_MASK = ",".join(
    [
        "suggestions.placePrediction.placeId",
        "suggestions.placePrediction.text.text",
        "suggestions.placePrediction.structuredFormat.mainText.text",
        "suggestions.placePrediction.structuredFormat.secondaryText.text",
    ]
)

_DETAILS_FIELD_MASK = ",".join(
    [
        "places.formattedAddress",
        "places.location",
    ]
)


class GooglePlacesProvider:
    """Autocomplete (New) + Place Details (New), normalized to our shapes."""

    name = "google_places"
    live = True

    def __init__(self) -> None:
        settings = get_settings()
        self._key = settings.google_maps_api_key
        self._client = make_client(timeout=10.0)

    async def autocomplete(
        self,
        query: str,
        language: str = "en",
        session: str | None = None,
        bias: GeoPoint | None = None,
        limit: int = 5,
    ) -> list[dict]:
        if not self._key:
            raise ProviderError("GOOGLE_MAPS_API_KEY is not configured")
        body: dict = {"input": query, "languageCode": language}
        if session:
            body["sessionToken"] = session
        if bias is not None:
            # Bias only, never a restriction: results outside the area stay
            # allowed (international search must not be geographically cut).
            body["locationBias"] = {
                "circle": {
                    "center": {
                        "latitude": bias.lat,
                        "longitude": bias.lon,
                    },
                    "radius": 50000.0,
                }
            }
        try:
            response = await self._client.post(
                "https://places.googleapis.com/v1/places:autocomplete",
                json=body,
                headers={
                    "X-Goog-Api-Key": self._key,
                    "X-Goog-FieldMask": _PREDICTION_FIELD_MASK,
                },
            )
            response.raise_for_status()
            payload = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            raise ProviderError(f"Places autocomplete failed: {exc}") from exc

        results: list[dict] = []
        for row in payload.get("suggestions", []):
            prediction = row.get("placePrediction")
            if not prediction:
                continue  # query predictions carry no place to route to
            label = (prediction.get("text") or {}).get("text")
            place_id = prediction.get("placeId")
            if not label or not place_id:
                continue
            results.append({"id": place_id, "label": label})
            if len(results) >= limit:
                break
        return results

    async def details(
        self, place_id: str, language: str = "en", session: str | None = None
    ) -> GeoPoint | None:
        """Resolve a selected prediction to real coordinates + formatted address."""
        if not self._key:
            raise ProviderError("GOOGLE_MAPS_API_KEY is not configured")
        params: dict[str, str] = {"languageCode": language}
        if session:
            params["sessionToken"] = session
        try:
            response = await self._client.get(
                f"https://places.googleapis.com/v1/places/{place_id}",
                params=params,
                headers={
                    "X-Goog-Api-Key": self._key,
                    "X-Goog-FieldMask": _DETAILS_FIELD_MASK,
                },
            )
            response.raise_for_status()
            row = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            raise ProviderError(f"Place details failed: {exc}") from exc
        location = row.get("location") or {}
        if "latitude" not in location or "longitude" not in location:
            return None
        lat, lon = location["latitude"], location["longitude"]
        return GeoPoint(
            lat=lat,
            lon=lon,
            tz=tz_at(lat, lon),
            name=row.get("formattedAddress"),
        )

    async def close(self) -> None:
        await self._client.aclose()
